FROM debian:stable-slim

RUN apt-get update
RUN apt-get install -y rawtherapee
RUN apt-get install -y python3 python3-pip
RUN python3 -m pip install dropbox
RUN python3 -m pip install Flask gunicorn

RUN mkdir /tiffs

COPY converter/main.py main.py
COPY ConnectionHandlerDropbox.py ConnectionHandlerDropbox.py
COPY ConnectionHandler.py ConnectionHandler.py

## Run the web service on container startup. Here we use the gunicorn
## webserver, with one worker process and 8 threads.
## For environments with multiple CPU cores, increase the number of workers
## to be equal to the cores available.
CMD exec gunicorn --bind :$PORT --workers 1 --threads 1 --timeout 0 main:app
